title: Design Ecologies P/L Environmental Sustainable Architecture
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6875
  brandStrength: 0.3125
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#787878'
    - '#59862e'
    - '#dfdfdf'
    - '#a8c08e'
  lightness: 0.9375
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: DEESArchitecture
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.14802
layout_spectrum: 0.04131535
