name: DEESArchitecture
favicon: null
layout_spectrum: 0.9245623853057623
typography_spectrum: 0.6121154355350882
title: Design Ecologies P/L Environmental Sustainable Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27663169405423105
  lightness: 0.9683062443509698
  saturation: 0.6811650379095227
  rhythmicContrast: 0.9667653262149543
purpose: []
