name: DEESArchitecture
favicon: null
layout_spectrum: 0.60569
typography_spectrum: 0.14802
title: Design Ecologies P/L Environmental Sustainable Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#787878'
    - '#59862e'
    - '#dfdfdf'
    - '#a8c08e'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
